subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm -Idrivers/staging/android

obj-$(CONFIG_MACH_SONY_SHUANG) += board-8610-shuang.o board-8610-shuang-gpiomux.o
obj-$(CONFIG_MACH_SONY_SHUANG) += board-8610-shuang-console.o
obj-$(CONFIG_MACH_SONY_SHUANG) += bms-batterydata-arima.o
