subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm -Idrivers/staging/android

obj-$(CONFIG_MACH_SONY_FALCONSS) += board-8610-falconss.o board-8610-falconss-gpiomux.o
obj-$(CONFIG_MACH_SONY_FALCONSS) += board-8610-falconss-console.o
obj-$(CONFIG_MACH_SONY_FALCONSS) += bms-batterydata-arima.o
